// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class ArticleGetByBlockIdResult
    {
        public int NoItem { get; set; }
        public int Id { get; set; }
        public int? ProductBrandId { get; set; }
        public int? ArticleTypeId { get; set; }
        public string ArticleCategoryIds { get; set; }
        public string Name { get; set; }
        public string SubTitle { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Author { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public bool? Active { get; set; }
        public int? Counter { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastEditBy { get; set; }
        public DateTime? LastEditDate { get; set; }
        public string URL { get; set; }
        public string Tags { get; set; }
    }
}
