// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class Article
    {
        [Key]
        public int Id { get; set; }
        public int? ArticleTypeId { get; set; }
        [StringLength(200)]
        public string ArticleCategoryIds { get; set; }
        public int? ProductBrandId { get; set; }
        public int? ArticleStatusId { get; set; }
        [StringLength(1000)]
        public string Name { get; set; }
        [StringLength(200)]
        public string SubTitle { get; set; }
        [StringLength(200)]
        public string Image { get; set; }
        [StringLength(200)]
        public string ImageDescription { get; set; }
        [StringLength(200)]
        public string BannerImage { get; set; }
        public string Description { get; set; }
        [Column(TypeName = "ntext")]
        public string Content { get; set; }
        [StringLength(200)]
        public string Author { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public bool? Active { get; set; }
        public int? Counter { get; set; }
        [StringLength(450)]
        public string CreateBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [StringLength(450)]
        public string LastEditBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastEditDate { get; set; }
        [StringLength(450)]
        public string CheckBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CheckDate { get; set; }
        [StringLength(450)]
        public string ApproveBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApproveDate { get; set; }
        [Column("URL")]
        [StringLength(1000)]
        public string Url { get; set; }
        public string Tags { get; set; }
        public bool? CanCopy { get; set; }
        public bool? CanComment { get; set; }
        public bool? CanDelete { get; set; }
        [StringLength(500)]
        public string MetaTitle { get; set; }
        [StringLength(500)]
        public string MetaDescription { get; set; }
        [StringLength(500)]
        public string MetaKeywords { get; set; }
        [StringLength(500)]
        public string DocumentRefer { get; set; }
    }
}