// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class Department
    {
        [Key]
        public int Id { get; set; }
        public int? ProductBrandId { get; set; }
        [StringLength(500)]
        public string Name { get; set; }
        public int? Sort { get; set; }
    }
}