// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    [Keyless]
    public partial class ReplaceChar
    {
        [Column("ReplaceChar_ID")]
        public int ReplaceCharId { get; set; }
        [StringLength(5)]
        public string OldChar { get; set; }
        [StringLength(1)]
        public string NewChar { get; set; }
    }
}