// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace CMS.Data.ModelEntity
{
    public partial class UserNotify
    {
        [Key]
        public int Id { get; set; }
        public int? UserNotifyTypeId { get; set; }
        [StringLength(450)]
        public string AspNetUsersId { get; set; }
        [StringLength(1000)]
        public string Subject { get; set; }
        [StringLength(2000)]
        public string Content { get; set; }
        [Column("URL")]
        [StringLength(500)]
        public string Url { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        public bool? Readed { get; set; }
        public int? ReadCount { get; set; }
        [StringLength(1000)]
        public string ImageUrl { get; set; }
    }
}