// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMS.Data.ModelEntity
{
    public partial class UserNotifySearchResult
    {
        public int NoItem { get; set; }
        public int Id { get; set; }
        public string AspNetUsersId { get; set; }
        public int? UserNotifyTypeId { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string URL { get; set; }
        public DateTime? CreateDate { get; set; }
        public bool? Readed { get; set; }
        public int? ReadCount { get; set; }
    }
}
